FROM ubuntu:focal
# Install some packages to facilitate the build process
RUN	apt-get -y update && \
	apt-get -y install \
		fuse \
		git \
		liblzo2-2 \
		mono-complete \
		rsync \
		wget \
		zsync
# The homedir for this user is required for nuget
RUN	groupadd builder --gid 1000 && \
	useradd builder --uid 1000 -g builder -d /home/builder -m
# Run the build script on container start
WORKDIR /opt
CMD [ "/bin/bash", "./tools/appimage/build.sh" ]
