from __future__ import annotations

from randovania.exporter.hints.joke_hints import GENERIC_JOKE_HINTS

FUSION_JOKE_HINTS = GENERIC_JOKE_HINTS + [
    "Space Pirates, strangely, dislike theft.",
    "We've been trying to contact you about your ship's extended warranty.",
    "Did you know Yellow X are lemon flavoured?",
    "Did you know Green X are lime flavoured?",
    "Did you know Red X are strawberry flavoured?",
    "Did you know Blue X are blueberry flavoured?",
    "I would tell you a hint, but Aran out of them.",
    "If you do not know where you are going, you are playing METROID CONFUSION.",
    "Someone who looked just like you already claimed this hint.",
    "The electrified water is quite shocking.",
    "The Galactic Federation put Ridley on ice.",
    "Don't boil over with excitement while exploring the Lava Maze.",
    "Did Gary touch the thermostat again?",
    "When the last Metroid is in Captivity, the galaxy will be at peace.",
    "Fulfill your destiny, Samus. This is an order. Disobedience will not be tolerated.",
    "The Galactic Federation was experimenting with Bioweapons. What happened here was illegal.",
    "Looks like your comm system is still functional. You know what to do. Go to it.",
    "You want a hint? Don't be so ridleyculous, Samus.",
    "Looks like this message Rippered you off.",
    "Use a Nintendo GameCube Game Boy Advance Cable to unlock content in Metroid Prime.",
    "Use a Game Boy Advance Game Link cable to unlock content in Metroid: Zero Mission.",
    "Use headphones for the optimal screaming experience.",
    "You can quickly navigate between Sectors by using TUUUUUUUUUUBES.",
    "Unsurprisingly, Owtches hurt.",
    "Check this out! This Baby Metroid is so squishy!",
    "Have you seen Bob yet?",
    "I forgot the next lines but they go:\nSecret tunnel~ Secret tunnel~ Through the Overgrown Spire~",
    "Arachnus is, despite the name, not a member of the Arachnid family.",
    "Samus, can you go to the fridge and get me some milk? I'm thirsty.",
    "Yellow is greener than red but both are equally blue.",
    "Keep a cool head while fighting the SA-X.",
    "Quickly moving left and right is not a Fusion Dance.",
    "Samus does not have an ADAM's apple.",
    "The Baby...",
    "I'm having a blast shooting missiles at enemies.",
    "When seeing spiders, my first Reaction is to jump.",
    "This Terminal cannot Navigate.",
    "Nettori's strength comes from its feet being planted into the ground.",
    "Zoros crawl around a corner and start flying.",
    "Samus can position herself with Zozoros to form a sandwich.",
    "You wouldn't steal an animal. You wouldn't steal a Core-X. You wouldn't download an Infant Metroid.",
    "Your next item is... hey, this hint is just an X in disguise!",
    "Before entering Sector 6, don't forget to NOC.",
    "If you see X-B.O.X., turn 360 degrees and walk away.",
    "WARNING: Excessive exposure to Puyos is known to cause fevers.",
    "The pickup pool is great! Water you waiting for?",
    "If you're struggling to defeat your enemies, think outside the B.O.X.",
    "Don't know what to do? Zeela vie.",
    "If something gets in your way, Choot it!",
    "Sometimes, it may not be possible to collect Evir-thing",
    "You humans have some funny little brains. How do you get around in those things?",
    "This hint isn't useful enough for you? Well, excuuuuuse me, princess!",
    "Lady, I love space. What's your favorite thing about space? Mine is space.",
    "The X are coming. With all their glory. And all their horror.",
    "Blue X move in mesmerizing ARCs.",
]
