# from randovania.games.samus_returns.gui.dialog.samus_returns_cosmetic_patches_dialog import SamusReturnsCosmeticPatchesDialog
# from randovania.games.samus_returns.gui.dialog.game_export_dialog import SamusReturnsGameExportDialog
from randovania.games.samus_returns.gui.samus_returns_game_tab import SamusReturnsGameTabWidget
# from randovania.games.samus_returns.gui.hint_details_tab import SamusReturnsHintDetailsTab