from randovania.games.samus_returns.gui.msr_game_tab import MSRGameTabWidget
from randovania.games.samus_returns.gui.dialog.cosmetic_patches_dialog import MSRCosmeticPatchesDialog
from randovania.games.samus_returns.gui.dialog.game_export_dialog import MSRGameExportDialog
from randovania.games.samus_returns.gui.preset_settings import preset_tabs