DEFAULT_INDICES_WEIGHT_MULTIPLIER = 1
DEFAULT_EVENTS_WEIGHT_MULTIPLIER = 0.5
DEFAULT_HINTS_WEIGHT_MULTIPLIER = 1

_DANGEROUS_ACTION_MULTIPLIER = 0.75
_ADDITIONAL_NODES_WEIGHT_MULTIPLIER = 0.01
_VICTORY_WEIGHT = 1000
