from randovania.games.prime2.gui.dialog.echoes_cosmetic_patches_dialog import EchoesCosmeticPatchesDialog
from randovania.games.prime2.gui.dialog.game_export_dialog import EchoesGameExportDialog
from randovania.games.prime2.gui.echoes_game_tab import EchoesGameTabWidget
from randovania.games.prime2.gui.hint_details_tab import EchoesHintDetailsTab
from randovania.games.prime2.gui.preset_settings import prime2_preset_tabs
from randovania.games.prime2.gui.translator_gate_details_tab import TranslatorGateDetailsTab
