from __future__ import annotations

from randovania.exporter.hints.joke_hints import GENERIC_JOKE_HINTS

ECHOES_JOKE_HINTS = GENERIC_JOKE_HINTS + [
    "Make sure to collect an Energy Transfer Module; otherwise your run won't be valid!",
    "Adam has not yet authorized the use of this hint.",
    "Hear the words of O-Lir, last Sentinel of the Fortress Temple. May they serve you well.",
    "Warning! Dark Aether's atmosphere is dangerous! Energized Safe Zones don't last forever!",
    "A really important item can be found at - (transmission ends)",
    "Did you know that Bigfoot and Santa Claus exist in the Metroid Prime canon?",
    "I hear. Them. Everywhere. They're coming. Can't sleep. Ever. They'll eat me. Eat.",
    "Space Pirates, strangely, dislike theft.",
    "Power Bomb Expansions are just space hamburgers.",
    "While in Morph Ball mode, press &image=SI,0.70,0.68,D523DE3B; to drop Bombs.",
    "Charge your beam to fire a normal shot when out of ammo.",
    "Movement in Morph Ball mode is faster than unmorphed, even without Boost Ball.",
    "While walking, holding L makes you move faster.",
    "We've been trying to contact you about your ship's extended warranty.",
    "The Scan Visor is useful for gathering information.",
    "Want to become famous? Buy follo... <Transmission blocked>",
    "The Dark Suit protects against the toxic atmosphere of Dark Aether.",
    "The Light Suit is fully resistant to the effects of Dark Aether.",
    "Your current Chozo Battle Suit version is SA1-4468-VM6-P.",
    "May the Light of Aether shine upon you!",
    "I would tell you a hint, but Aran out of them.",
    "Humans will get mad when noticing that they're breathing manually. The Ing don't have such weaknesses!",
    "We now pledge sole allegiance to our liberator, the great one, Dark Samus.",
    "Defeat enemies with the Light Beam to earn Dark Ammo. Defeat enemies with the Dark Beam to earn Light Ammo.",
    "Your Friend Roster is currently empty.",
    "Raven Beak? I don't know him, but he sounds handsome, wouldn't you agree Samus?",
    "Long ago, the creatures on Aether lived together in harmony. Then, everything changed when the Ing attacked.",
    "After a 40 day trial period you must either buy a license or remove the Chozo firmware from your Power Suit.",
    "Dark Pirate Commandos can be quickly defeated with a charged Dark Beam shot followed by a Missile.",
    "For you, the day the Ing graced Aether was the most important day of your life. But for us, it was Tuesday.",
    "Be kind to Lightbringers.",
    "Imagine the confusion reading reports of 'Death due to Splinter'.",
    "The band of Torvus consists of amazing Shredders.",
    "Follow my Blogg for more swimming tips!",
    "Quadraxis is a leg-endary boss.",
    "I always just wing the fight against Chykka.",
    "Sometimes you just gotta admire your opponents' Ing-credible power.",
    "Morphing and staying still may attract some flying friends.",
    "Amorbis really digs raves.",
    "Navigating Dark Aether with low health causes Agon-y.",
]
